import { useMemo, useState, type ReactNode } from 'react';
import { useMutation } from '@tanstack/react-query';
import * as XLSX from 'xlsx';
import { toast } from 'sonner';
import { ArrowRight, Boxes, CalendarDays, ClipboardCheck, Download, Eye, FileDown, History, Landmark, Package, Plus, RefreshCw, Search, Scale, ShieldCheck, TrendingDown, TrendingUp, Warehouse, Wrench } from 'lucide-react';
import { useTenantQuery } from '../../hooks/useTenantQuery';
import { enterpriseGroupsService, type ManagerInventoryModuleResponse } from '../../services/enterprise-groups.service';
import { Badge } from '../ui/badge';
import { Button } from '../ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '../ui/card';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '../ui/dialog';
import { Input } from '../ui/input';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '../ui/table';
import { Tabs, TabsList, TabsTrigger } from '../ui/tabs';
import { ManagerInventoryAdjustmentsView } from './ManagerInventoryAdjustmentsView';
import { MANAGER_INVENTORY_VIEWS, type ManagerInventoryView } from './manager-inventory.types';
import { useManagerShellNavigation } from '../ManagerShell';

type BranchOption = { id: string; name: string; businessUnitId?: string | null };
type WarehouseOption = { id: string; name: string; scopeType: string; clientTenantId: string | null; businessUnitId?: string | null; authorizedBranchIds?: string[] };

const viewLabels: Record<ManagerInventoryView, string> = {
  overview: 'Resumen de inventario', branchInventory: 'Inventario de mi sucursal', corporateInventory: 'Inventario de almacén corporativo', products: 'Productos', services: 'Servicios', warehouses: 'Bodegas', corporateWarehouses: 'Almacenes', transfers: 'Transferencias', adjustments: 'Ajustes', audits: 'Auditorías', losses: 'Pérdidas', movements: 'Movimientos', assets: 'Mobiliario y equipos',
};
const statusLabels: Record<string, string> = { PENDING: 'Pendiente', IN_TRANSIT: 'En tránsito', COMPLETED: 'Completada', APPROVED: 'Aprobada', CANCELLED: 'Cancelada', OPEN: 'Abierta', IN_PROGRESS: 'En progreso', CLOSED: 'Cerrada', REOPENED: 'Reabierta', DISPOSED: 'Dada de baja', DAMAGED: 'Dañada' };
const formatStatus = (value: unknown) => statusLabels[String(value || '').toUpperCase()] || String(value || '—');
const formatNumber = (value: unknown) => new Intl.NumberFormat('es-NI', { maximumFractionDigits: 2 }).format(Number(value || 0));
const formatMoney = (value: unknown, currency = 'NIO') => `${currency} ${formatNumber(value)}`;
const formatDate = (value: unknown) => value ? new Intl.DateTimeFormat('es-NI', { dateStyle: 'short', timeStyle: 'short' }).format(new Date(String(value))) : '—';
const viewIcon = (view: ManagerInventoryView) => ({ overview: Boxes, branchInventory: Package, corporateInventory: Warehouse, products: Package, services: Wrench, warehouses: Warehouse, corporateWarehouses: Warehouse, transfers: ArrowRight, adjustments: Scale, audits: ClipboardCheck, losses: TrendingDown, movements: History, assets: Landmark }[view]);

export function ManagerInventoryModule({ view, onViewChange, groupId, businessUnitId, branchId, branches, warehouses, canCreateTransfers, corporateWarehouseContent }: { view: ManagerInventoryView; onViewChange: (view: ManagerInventoryView) => void; groupId: string; businessUnitId?: string; branchId?: string; branches: BranchOption[]; warehouses: WarehouseOption[]; canCreateTransfers: boolean; corporateWarehouseContent?: ReactNode }) {
  const { sidebarCollapsed } = useManagerShellNavigation();
  const [search, setSearch] = useState('');
  const [status, setStatus] = useState('');
  const [movementType, setMovementType] = useState('');
  const [warehouseId, setWarehouseId] = useState('');
  const [dateFrom, setDateFrom] = useState('');
  const [dateTo, setDateTo] = useState('');
  const [page, setPage] = useState(1);
  const [detail, setDetail] = useState<any | null>(null);
  const [createTransferOpen, setCreateTransferOpen] = useState(false);
  const [sourceBranchId, setSourceBranchId] = useState(branchId || branches[0]?.id || '');
  const [destBranchId, setDestBranchId] = useState(branchId || branches[0]?.id || '');
  const [fromWarehouseId, setFromWarehouseId] = useState('');
  const [toWarehouseId, setToWarehouseId] = useState('');
  const [transferProductId, setTransferProductId] = useState('');
  const [transferQuantity, setTransferQuantity] = useState('1');
  const [exporting, setExporting] = useState(false);
  const [refreshKey, setRefreshKey] = useState(0);
  const moduleQuery = useTenantQuery(
    ['manager-inventory-module', groupId, view, businessUnitId || 'all', branchId || 'all', warehouseId || 'all', status || 'all', movementType || 'all', search, dateFrom, dateTo, page],
    (signal) => enterpriseGroupsService.getInventoryModule(groupId, { view, businessUnitId, branchId, warehouseId, status: status || undefined, type: movementType || undefined, search, dateFrom, dateTo, page, pageSize: 25 }, signal),
    { enabled: Boolean(groupId) && view !== 'adjustments' && view !== 'corporateWarehouses' },
  );
  const response = moduleQuery.data as ManagerInventoryModuleResponse | undefined;
  const rows = response?.data || [];
  const metrics = response?.metrics || {};
  const activeViewLabel = viewLabels[view];
  const branchWarehouseCount = warehouses.filter((warehouse) => Boolean(warehouse.clientTenantId)).length;
  const corporateWarehouseCount = warehouses.filter((warehouse) => !warehouse.clientTenantId).length;

  const transferProductsQuery = useTenantQuery(
    ['manager-inventory-transfer-products', groupId, businessUnitId || 'all', sourceBranchId],
    (signal) => enterpriseGroupsService.getInventoryModule(groupId, { view: 'branchInventory', businessUnitId, branchId: sourceBranchId, report: true, page: 1, pageSize: 5000 }, signal),
    { enabled: view === 'transfers' && createTransferOpen && Boolean(sourceBranchId) },
  );
  const transferProducts = transferProductsQuery.data?.data || [];
  const sourceWarehouses = useMemo(() => warehousesForBranch(warehouses, sourceBranchId), [warehouses, sourceBranchId]);
  const destinationWarehouses = useMemo(() => warehousesForBranch(warehouses, destBranchId), [warehouses, destBranchId]);
  const visibleWarehouses = useMemo(() => warehouses.filter((warehouse) => !businessUnitId || !warehouse.businessUnitId || warehouse.businessUnitId === businessUnitId), [warehouses, businessUnitId]);

  const transferMutation = useMutation({
    mutationFn: () => enterpriseGroupsService.createInterTenantTransfer(groupId, { sourceBranchId, destBranchId, fromWarehouseId, toWarehouseId, items: [{ productId: transferProductId, quantity: Number(transferQuantity) }] }),
    onSuccess: () => { toast.success('Transferencia creada'); setCreateTransferOpen(false); setTransferProductId(''); setTransferQuantity('1'); void moduleQuery.refetch(); },
    onError: (error: Error) => toast.error(error.message),
  });

  const updateFilter = (setter: (value: string) => void, value: string) => { setter(value); setPage(1); };
  const clearFilters = () => { setSearch(''); setStatus(''); setMovementType(''); setWarehouseId(''); setDateFrom(''); setDateTo(''); setPage(1); };

  const exportReport = async () => {
    setExporting(true);
    try {
      const report = await enterpriseGroupsService.getInventoryModule(groupId, { view, businessUnitId, branchId, warehouseId, status: status || undefined, type: movementType || undefined, search, dateFrom, dateTo, report: true, page: 1, pageSize: 5000 });
      const exportRows = report.data.map((row: any) => exportRow(view, row));
      if (!exportRows.length) { toast.info('No hay datos para exportar'); return; }
      const workbook = XLSX.utils.book_new();
      XLSX.utils.book_append_sheet(workbook, XLSX.utils.json_to_sheet(exportRows), viewLabels[view].slice(0, 31));
      XLSX.writeFile(workbook, `inventario-manager-${view}-${new Date().toISOString().slice(0, 10)}.xlsx`);
    } catch (error) {
      toast.error(error instanceof Error ? error.message : 'No se pudo generar el reporte');
    } finally {
      setExporting(false);
    }
  };

  const hasFilters = Boolean(search || status || movementType || warehouseId || dateFrom || dateTo);
  return <div className="inventory-module mx-auto min-w-0 w-full max-w-[1700px] space-y-4 overflow-x-hidden p-3 pb-20 sm:p-6 md:p-10">
    <div className="flex min-w-0 flex-col gap-4 md:flex-row md:items-center md:justify-between">
      <div className="flex min-w-0 items-center gap-3">
        <div className="flex size-[66px] shrink-0 items-center justify-center rounded-xl bg-primary/10"><Boxes className="size-9 text-primary" /></div>
        <div className="min-w-0">
          <h1 className="flex flex-wrap items-center gap-x-3 gap-y-1 text-3xl font-black uppercase italic leading-none tracking-tighter sm:text-4xl">Inventario <span className="text-primary">de Mercancías</span></h1>
          <p className="mt-2 text-sm text-muted-foreground">Consulta existencias, almacenes y movimientos separados por rubro, sucursal y alcance.</p>
          <div className="mt-2 flex items-center gap-2"><Badge className="border-primary/20 bg-primary/10 px-3 py-1 text-[10px] font-black uppercase tracking-widest text-primary">{branches.length} sucursales · {branchWarehouseCount} bodegas · {corporateWarehouseCount} almacenes corporativos · vista Manager</Badge></div>
        </div>
      </div>
      <div className="flex w-full flex-wrap items-center gap-2 md:w-auto md:justify-end">
        <Button type="button" variant="outline" size="sm" className="min-w-0 flex-1 rounded-xl font-bold sm:flex-none" onClick={() => { setRefreshKey((current) => current + 1); void moduleQuery.refetch(); }} disabled={moduleQuery.isFetching}><RefreshCw className={`mr-2 size-4 ${moduleQuery.isFetching ? 'animate-spin' : ''}`} />Actualizar</Button>
        {view !== 'corporateWarehouses' && <Button type="button" variant="outline" size="sm" className="min-w-0 flex-1 rounded-xl font-bold sm:flex-none" onClick={exportReport} disabled={exporting || moduleQuery.isLoading}><Download className="mr-2 size-4" />{exporting ? 'Preparando…' : 'Exportar'}</Button>}
      </div>
    </div>

    {sidebarCollapsed && <Tabs value={view} onValueChange={(value) => onViewChange(value as ManagerInventoryView)} className="w-full">
      <div className="mb-6 w-full overflow-x-auto custom-scrollbar">
        <TabsList className="flex h-auto w-max min-w-full gap-1.5 rounded-2xl border border-border/40 bg-gradient-to-br from-muted/30 to-muted/50 p-1.5 backdrop-blur-sm [&>button]:flex-none [&>button]:shrink-0 [&>button]:text-muted-foreground [&>button]:hover:bg-muted/50 [&>button]:hover:text-foreground sm:min-w-0">
          {MANAGER_INVENTORY_VIEWS.map((item) => { const Icon = viewIcon(item.id); return <TabsTrigger key={item.id} value={item.id} className="flex items-center gap-2 rounded-xl px-4 py-2.5 text-xs font-black uppercase tracking-widest transition-all data-[state=active]:bg-gradient-to-br data-[state=active]:from-primary data-[state=active]:to-primary/80 data-[state=active]:text-primary-foreground data-[state=active]:shadow-lg"><Icon className="size-4" /><span className="hidden sm:inline">{item.label}</span></TabsTrigger>; })}
        </TabsList>
      </div>
    </Tabs>}

    <div className="flex min-w-0 flex-col gap-1 px-1">
      <h2 className="text-2xl font-black uppercase italic leading-none tracking-tight">{activeViewLabel}</h2>
      <p className="text-sm text-muted-foreground">Información del rubro seleccionado dentro del alcance autorizado.</p>
    </div>

    {view === 'corporateWarehouses' ? corporateWarehouseContent : view === 'adjustments' ? <ManagerInventoryAdjustmentsView groupId={groupId} businessUnitId={businessUnitId} branchId={branchId} branches={branches} warehouses={warehouses} embedded refreshKey={refreshKey} /> : <>

    <Metrics view={view} metrics={metrics} branchWarehouseCount={branchWarehouseCount} />
    {view !== 'overview' && <Card className="rounded-3xl border-border/60 shadow-sm"><CardHeader className="gap-4 pb-4"><CardTitle className="flex items-center gap-2 text-base font-black uppercase italic tracking-tight"><Search className="size-5 text-primary" />Filtros de consulta</CardTitle><div className="grid min-w-0 grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-6"><label className="min-w-0 space-y-1.5 text-xs font-bold text-muted-foreground xl:col-span-2"><span>Buscar</span><div className="relative"><Search className="pointer-events-none absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><Input value={search} onChange={(event) => updateFilter(setSearch, event.target.value)} placeholder="Código, nombre, número…" className="pl-9" /></div></label>{['transfers', 'audits', 'losses', 'assets'].includes(view) && <FilterSelect label="Estado" value={status} onChange={(value) => updateFilter(setStatus, value)} options={Object.entries(statusLabels).map(([value, label]) => ({ value, label }))} />}{view === 'movements' && <FilterSelect label="Tipo de movimiento" value={movementType} onChange={(value) => updateFilter(setMovementType, value)} options={[{ value: 'IN', label: 'Entrada' }, { value: 'OUT', label: 'Salida' }, { value: 'TRANSFER_IN', label: 'Transferencia entrada' }, { value: 'TRANSFER_OUT', label: 'Transferencia salida' }, { value: 'ADJUSTMENT', label: 'Ajuste' }]} />}{!['products', 'services'].includes(view) && <FilterSelect label="Almacén / bodega" value={warehouseId} onChange={(value) => updateFilter(setWarehouseId, value)} options={visibleWarehouses.map((warehouse) => ({ value: warehouse.id, label: warehouse.name }))} />}{['transfers', 'audits', 'losses', 'movements'].includes(view) && <DateFilter label="Desde" value={dateFrom} onChange={(value) => updateFilter(setDateFrom, value)} />}{['transfers', 'audits', 'losses', 'movements'].includes(view) && <DateFilter label="Hasta" value={dateTo} onChange={(value) => updateFilter(setDateTo, value)} />}</div><div className="flex flex-wrap items-center justify-between gap-2 text-xs text-muted-foreground"><span>{response?.meta.total || 0} registro(s) en el alcance seleccionado</span>{hasFilters && <Button type="button" variant="ghost" size="sm" className="rounded-lg" onClick={clearFilters}>Limpiar filtros</Button>}</div></CardHeader></Card>}

    {view === 'overview' && <OverviewPanel metrics={metrics} branches={branches} warehouses={warehouses} />}
    {moduleQuery.isLoading && <div className="flex min-h-[240px] items-center justify-center text-muted-foreground"><RefreshCw className="mr-2 size-5 animate-spin" />Cargando vista del alcance…</div>}
    {moduleQuery.isError && <Card className="rounded-3xl border-destructive/40"><CardContent className="p-10 text-center text-sm text-destructive">No se pudo cargar esta vista. {moduleQuery.error.message}</CardContent></Card>}
    {!moduleQuery.isLoading && !moduleQuery.isError && view !== 'overview' && !rows.length && <Card className="rounded-3xl border-dashed"><CardContent className="p-10 text-center text-sm text-muted-foreground">No hay información para el alcance y filtros seleccionados.</CardContent></Card>}
    {!moduleQuery.isLoading && !moduleQuery.isError && rows.length > 0 && <ViewTable view={view} rows={rows} onDetail={setDetail} onCreateTransfer={canCreateTransfers ? () => { setSourceBranchId(branchId || branches[0]?.id || ''); setDestBranchId(branchId || branches[0]?.id || ''); setCreateTransferOpen(true); } : undefined} />}
    {response?.meta && response.meta.totalPages > 1 && <Pagination page={response.meta.page} totalPages={response.meta.totalPages} onChange={setPage} />}

    <DetailDialog view={view} row={detail} onClose={() => setDetail(null)} />
    {view === 'transfers' && canCreateTransfers && <Dialog open={createTransferOpen} onOpenChange={setCreateTransferOpen}><DialogContent className="max-w-3xl rounded-3xl"><DialogHeader><DialogTitle className="text-xl font-black uppercase italic">Nueva transferencia</DialogTitle><DialogDescription>Transfiere existencias entre una bodega de sucursal y un almacén corporativo, o entre dos ubicaciones autorizadas del mismo rubro.</DialogDescription></DialogHeader><div className="grid min-w-0 grid-cols-1 gap-4 sm:grid-cols-2"><SelectField label="Sucursal origen" value={sourceBranchId} onChange={(value) => { setSourceBranchId(value); setFromWarehouseId(''); }} options={branches.map((branch) => ({ value: branch.id, label: branch.name }))} /><SelectField label="Sucursal destino" value={destBranchId} onChange={(value) => { setDestBranchId(value); setToWarehouseId(''); }} options={branches.map((branch) => ({ value: branch.id, label: branch.name }))} /><SelectField label="Origen" value={fromWarehouseId} onChange={setFromWarehouseId} options={sourceWarehouses.map((warehouse) => ({ value: warehouse.id, label: warehouse.name }))} /><SelectField label="Destino" value={toWarehouseId} onChange={setToWarehouseId} options={destinationWarehouses.map((warehouse) => ({ value: warehouse.id, label: warehouse.name }))} /><SelectField label="Producto" value={transferProductId} onChange={setTransferProductId} options={transferProducts.map((product: any) => ({ value: product.productId || product.id, label: `${product.code} · ${product.name}` }))} /><label className="space-y-1.5 text-xs font-bold text-muted-foreground"><span>Cantidad</span><Input type="number" min="0.01" step="0.01" value={transferQuantity} onChange={(event) => setTransferQuantity(event.target.value)} /></label></div><DialogFooter><Button type="button" variant="outline" className="rounded-xl" onClick={() => setCreateTransferOpen(false)}>Cancelar</Button><Button type="button" className="rounded-xl" disabled={!sourceBranchId || !destBranchId || !fromWarehouseId || !toWarehouseId || !transferProductId || Number(transferQuantity) <= 0 || transferMutation.isPending} onClick={() => transferMutation.mutate()}>{transferMutation.isPending ? 'Creando…' : 'Crear transferencia'}</Button></DialogFooter></DialogContent></Dialog>}
    </>}
  </div>;
}

function Metrics({ view, metrics, branchWarehouseCount }: { view: ManagerInventoryView; metrics: Record<string, number>; branchWarehouseCount: number }) {
  const cards: Array<{ label: string; value: unknown; icon: any; tone?: string }> = view === 'overview'
    ? [{ label: 'Productos', value: metrics.products, icon: Package }, { label: 'Servicios', value: metrics.services, icon: Wrench, tone: 'text-sky-600 bg-sky-500/10' }, { label: 'Stock de mi sucursal', value: metrics.branchInventoryUnits, icon: Package, tone: 'text-emerald-600 bg-emerald-500/10' }, { label: 'Stock corporativo', value: metrics.corporateInventoryUnits, icon: Warehouse, tone: 'text-violet-600 bg-violet-500/10' }, { label: 'Bodegas', value: branchWarehouseCount, icon: Warehouse, tone: 'text-amber-600 bg-amber-500/10' }, { label: 'Transferencias', value: metrics.transfers, icon: ArrowRight, tone: 'text-violet-600 bg-violet-500/10' }, { label: 'Movimientos', value: metrics.movements, icon: History, tone: 'text-cyan-600 bg-cyan-500/10' }, { label: 'Auditorías', value: metrics.audits, icon: ClipboardCheck, tone: 'text-orange-600 bg-orange-500/10' }]
    : view === 'branchInventory' || view === 'corporateInventory'
      ? [{ label: 'Líneas visibles', value: metrics.lines, icon: Package }, { label: 'Productos', value: metrics.products, icon: ShieldCheck, tone: 'text-sky-600 bg-sky-500/10' }, { label: 'Stock disponible', value: metrics.availableUnits, icon: Boxes, tone: view === 'branchInventory' ? 'text-emerald-600 bg-emerald-500/10' : 'text-violet-600 bg-violet-500/10' }, { label: 'Reservado', value: metrics.reservedUnits, icon: Scale, tone: 'text-amber-600 bg-amber-500/10' }]
    : view === 'products' || view === 'services'
      ? [{ label: view === 'products' ? 'Productos por sucursal' : 'Servicios', value: metrics.products, icon: view === 'products' ? Package : Wrench }, { label: 'Sucursales', value: metrics.branches, icon: ShieldCheck, tone: 'text-sky-600 bg-sky-500/10' }, { label: 'Bodegas', value: branchWarehouseCount, icon: Warehouse, tone: 'text-amber-600 bg-amber-500/10' }, { label: view === 'products' ? 'Stock de sucursal' : 'Unidades', value: metrics.inventoryUnits, icon: Boxes, tone: 'text-emerald-600 bg-emerald-500/10' }, { label: 'Valor al costo', value: formatMoney(metrics.inventoryValue), icon: Scale, tone: 'text-violet-600 bg-violet-500/10' }]
      : view === 'warehouses' ? [{ label: 'Ubicaciones activas', value: metrics.warehouses, icon: Warehouse }, { label: 'Almacenes corporativos', value: metrics.corporateWarehouses, icon: Landmark, tone: 'text-violet-600 bg-violet-500/10' }, { label: 'Bodegas de sucursal', value: metrics.branchWarehouses, icon: Boxes, tone: 'text-amber-600 bg-amber-500/10' }, { label: 'Sucursales abastecidas', value: metrics.linkedBranches, icon: ShieldCheck, tone: 'text-emerald-600 bg-emerald-500/10' }, { label: 'Unidades ubicadas', value: metrics.inventoryUnits, icon: Package, tone: 'text-sky-600 bg-sky-500/10' }]
      : view === 'transfers' ? [{ label: 'Transferencias', value: metrics.transfers, icon: ArrowRight }, { label: 'Pendientes', value: metrics.pending, icon: RefreshCw, tone: 'text-amber-600 bg-amber-500/10' }, { label: 'Completadas', value: metrics.completed, icon: ShieldCheck, tone: 'text-emerald-600 bg-emerald-500/10' }, { label: 'Unidades movilizadas', value: metrics.units, icon: Boxes, tone: 'text-sky-600 bg-sky-500/10' }]
      : view === 'audits' ? [{ label: 'Auditorías', value: metrics.audits, icon: ClipboardCheck }, { label: 'Abiertas', value: metrics.open, icon: Search, tone: 'text-amber-600 bg-amber-500/10' }, { label: 'En progreso', value: metrics.inProgress, icon: RefreshCw, tone: 'text-sky-600 bg-sky-500/10' }, { label: 'Diferencia registrada', value: metrics.differences, icon: Scale, tone: 'text-rose-600 bg-rose-500/10' }]
      : view === 'losses' ? [{ label: 'Registros con pérdida', value: metrics.losses, icon: TrendingDown, tone: 'text-rose-600 bg-rose-500/10' }, { label: 'Unidades perdidas', value: metrics.units, icon: Boxes, tone: 'text-amber-600 bg-amber-500/10' }, { label: 'Productos afectados', value: metrics.products, icon: Package }, { label: 'Monto de pérdida', value: formatMoney(metrics.amount), icon: Scale, tone: 'text-violet-600 bg-violet-500/10' }]
      : view === 'movements' ? [{ label: 'Movimientos', value: metrics.movements, icon: History }, { label: 'Entradas', value: metrics.entries, icon: TrendingUp, tone: 'text-emerald-600 bg-emerald-500/10' }, { label: 'Salidas', value: metrics.exits, icon: TrendingDown, tone: 'text-rose-600 bg-rose-500/10' }, { label: 'Unidades salientes', value: metrics.unitsOut, icon: Boxes, tone: 'text-amber-600 bg-amber-500/10' }]
      : [{ label: 'Activos registrados', value: metrics.assets, icon: Wrench }, { label: 'Activos activos', value: metrics.active, icon: ShieldCheck, tone: 'text-emerald-600 bg-emerald-500/10' }, { label: 'Valor acumulado', value: formatMoney(metrics.value), icon: Landmark, tone: 'text-violet-600 bg-violet-500/10' }];
  return <div className="grid min-w-0 grid-cols-1 gap-3 sm:grid-cols-2 xl:grid-cols-4">{cards.map((card) => <Card key={card.label} className="rounded-2xl border-border/60 shadow-sm"><CardContent className="flex min-w-0 items-center gap-3 p-4"><div className={`flex size-10 shrink-0 items-center justify-center rounded-xl ${card.tone || 'text-primary bg-primary/10'}`}><card.icon className="size-5" /></div><div className="min-w-0"><p className="truncate text-[10px] font-black uppercase tracking-widest text-muted-foreground">{card.label}</p><p className="mt-1 truncate text-xl font-black tracking-tight">{card.value === undefined ? '—' : typeof card.value === 'number' ? formatNumber(card.value) : card.value}</p></div></CardContent></Card>)}</div>;
}

function OverviewPanel({ metrics, branches, warehouses }: { metrics: Record<string, number>; branches: BranchOption[]; warehouses: WarehouseOption[] }) {
  return <Card className="rounded-3xl border-border/60 bg-gradient-to-br from-primary/5 via-card to-card shadow-sm"><CardContent className="grid min-w-0 gap-6 p-5 md:grid-cols-[minmax(0,1fr)_minmax(260px,360px)] md:p-7"><div><p className="text-xs font-black uppercase tracking-[0.2em] text-primary">Mapa operativo</p><h3 className="mt-2 text-2xl font-black uppercase italic tracking-tight">Existencias con contexto</h3><p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">El Manager puede leer el catálogo compartido dentro del rubro, la existencia por sucursal y el desglose por bodega o almacén autorizado. Las cuentas de cada sucursal siguen separadas.</p><div className="mt-5 flex flex-wrap gap-2">{branches.map((branch) => <Badge key={branch.id} variant="outline" className="rounded-full px-3 py-1">{branch.name}</Badge>)}{!branches.length && <span className="text-sm text-muted-foreground">No hay sucursales visibles.</span>}</div></div><div className="rounded-2xl border border-border/60 bg-background/70 p-4"><p className="text-xs font-black uppercase tracking-widest text-muted-foreground">Alcance físico</p><div className="mt-4 space-y-3">{warehouses.slice(0, 5).map((warehouse) => <div key={warehouse.id} className="flex items-start gap-3"><div className="mt-0.5 flex size-8 shrink-0 items-center justify-center rounded-lg bg-primary/10 text-primary"><Warehouse className="size-4" /></div><div className="min-w-0"><p className="truncate text-sm font-semibold">{warehouse.name}</p><p className="text-xs text-muted-foreground">{warehouse.scopeType === 'BUSINESS_UNIT' ? 'Almacén corporativo' : 'Bodega de sucursal'}</p></div></div>)}{!warehouses.length && <p className="text-sm text-muted-foreground">No hay ubicaciones visibles.</p>}</div></div></CardContent></Card>;
}

function ViewTable({ view, rows, onDetail, onCreateTransfer }: { view: ManagerInventoryView; rows: any[]; onDetail: (row: any) => void; onCreateTransfer?: () => void }) {
  if (view === 'branchInventory' || view === 'corporateInventory') {
    const corporate = view === 'corporateInventory';
    return <Card className="rounded-3xl border-border/60 shadow-sm"><CardHeader><CardTitle className="flex flex-wrap items-center gap-2 text-lg font-black uppercase italic tracking-tight"><span>{corporate ? 'Inventario de almacén corporativo' : 'Inventario de mi sucursal'}</span><Badge variant="outline" className="normal-case not-italic">Stock independiente</Badge></CardTitle><p className="text-sm text-muted-foreground">{corporate ? 'Existencias de abastecimiento del almacén autorizado para esta sucursal.' : 'Existencias físicas disponibles en la sucursal seleccionada.'}</p></CardHeader><CardContent className="p-0"><ResponsiveTable><TableHeader><TableRow><TableHead>Producto</TableHead><TableHead>Código / SKU</TableHead><TableHead>{corporate ? 'Almacén corporativo' : 'Bodega de sucursal'}</TableHead><TableHead>Sucursal</TableHead><TableHead>Stock</TableHead><TableHead>Reservado</TableHead><TableHead>Disponible</TableHead><TableHead /></TableRow></TableHeader><TableBody>{rows.map((row) => <TableRow key={row.id}><TableCell><p className="font-semibold">{row.name}</p><p className="text-xs text-muted-foreground">{row.variantName || row.unit}</p></TableCell><TableCell><span className="font-mono font-bold">{row.code}</span><p className="text-xs text-muted-foreground">{row.sku || '—'}</p></TableCell><TableCell>{row.warehouseName}</TableCell><TableCell>{row.branchName}</TableCell><TableCell className="font-black">{formatNumber(row.quantity)}</TableCell><TableCell>{formatNumber(row.reserved)}</TableCell><TableCell className="font-black text-emerald-600">{formatNumber(row.available)}</TableCell><TableCell className="text-right"><Button variant="ghost" size="sm" className="rounded-lg" onClick={() => onDetail(row)}><Eye className="mr-1.5 size-4" />Detalle</Button></TableCell></TableRow>)}</TableBody></ResponsiveTable></CardContent></Card>;
  }
  if (view === 'transfers') return <Card className="rounded-3xl border-border/60 shadow-sm"><CardHeader className="flex flex-row items-center justify-between gap-3"><CardTitle className="text-lg font-black uppercase italic tracking-tight">Historial de transferencias</CardTitle>{onCreateTransfer && <Button type="button" className="rounded-xl" onClick={onCreateTransfer}><Plus className="mr-2 size-4" />Nueva transferencia</Button>}</CardHeader><CardContent className="p-0"><ResponsiveTable><TableHeader><TableRow><TableHead>Transferencia</TableHead><TableHead>Fecha</TableHead><TableHead>Origen</TableHead><TableHead>Destino</TableHead><TableHead>Productos</TableHead><TableHead>Unidades</TableHead><TableHead>Estado</TableHead><TableHead /></TableRow></TableHeader><TableBody>{rows.map((row) => <TableRow key={row.id}><TableCell className="font-bold">{row.number}</TableCell><TableCell>{formatDate(row.date)}</TableCell><TableCell>{row.from?.name || '—'}<p className="text-xs text-muted-foreground">{row.sourceBranchName}</p></TableCell><TableCell>{row.to?.name || '—'}</TableCell><TableCell>{formatNumber(row.itemCount)}</TableCell><TableCell>{formatNumber(row.units)}</TableCell><TableCell><Badge variant="outline">{formatStatus(row.status)}</Badge></TableCell><TableCell className="text-right"><Button variant="ghost" size="sm" className="rounded-lg" onClick={() => onDetail(row)}><Eye className="mr-1.5 size-4" />Detalle</Button></TableCell></TableRow>)}</TableBody></ResponsiveTable></CardContent></Card>;
  if (view === 'products' || view === 'services') return <Card className="rounded-3xl border-border/60 shadow-sm"><CardHeader><CardTitle className="text-lg font-black uppercase italic tracking-tight">{view === 'products' ? 'Catálogo por sucursal · stock separado' : 'Catálogo de servicios'}</CardTitle></CardHeader><CardContent className="p-0"><ResponsiveTable><TableHeader><TableRow><TableHead>Sucursal</TableHead><TableHead>Código</TableHead><TableHead>Producto / servicio</TableHead><TableHead>Categoría</TableHead><TableHead>Unidad</TableHead><TableHead>Costo</TableHead><TableHead>{view === 'products' ? 'Stock de sucursal' : 'Unidades'}</TableHead><TableHead>Disponible</TableHead><TableHead>Ubicaciones</TableHead><TableHead /></TableRow></TableHeader><TableBody>{rows.map((row) => <TableRow key={row.id}><TableCell>{row.branchName || '—'}</TableCell><TableCell className="font-mono font-bold">{row.code}</TableCell><TableCell><p className="font-semibold">{row.name}</p><p className="text-xs text-muted-foreground">{row.branchCount} sucursal(es)</p></TableCell><TableCell>{row.category}</TableCell><TableCell>{row.unit}</TableCell><TableCell>{formatMoney(row.costPrice)}</TableCell><TableCell>{view === 'products' ? formatNumber(row.branchStock) : '—'}</TableCell><TableCell className="font-bold text-emerald-600">{view === 'products' ? formatNumber(row.branchAvailable) : '—'}</TableCell><TableCell>{formatNumber(row.locationCount)}</TableCell><TableCell className="text-right"><Button variant="ghost" size="sm" className="rounded-lg" onClick={() => onDetail(row)}><Eye className="mr-1.5 size-4" />Detalle</Button></TableCell></TableRow>)}</TableBody></ResponsiveTable></CardContent></Card>;
  if (view === 'warehouses') return <Card className="rounded-3xl border-border/60 shadow-sm"><CardHeader><CardTitle className="text-lg font-black uppercase italic tracking-tight">Bodegas y almacenes por rubro</CardTitle></CardHeader><CardContent className="grid min-w-0 grid-cols-1 gap-3 p-5 md:grid-cols-2 xl:grid-cols-3">{rows.map((row) => <button type="button" key={row.id} onClick={() => onDetail(row)} className="min-w-0 rounded-2xl border border-border/60 bg-card p-4 text-left transition-colors hover:border-primary/40 hover:bg-primary/5"><div className="flex items-start justify-between gap-3"><div className="flex min-w-0 items-center gap-3"><div className="flex size-10 shrink-0 items-center justify-center rounded-xl bg-primary/10 text-primary"><Warehouse className="size-5" /></div><div className="min-w-0"><p className="truncate font-bold">{row.name}</p><p className="truncate text-xs text-muted-foreground">{row.businessUnitName || 'Sin rubro'}</p></div></div><Badge variant="outline">{row.isCorporate ? 'Corporativo' : 'Bodega'}</Badge></div><div className="mt-4 grid grid-cols-2 gap-2 text-xs"><div className="rounded-xl bg-muted/30 px-3 py-2"><p className="text-muted-foreground">Stock visible</p><p className="mt-1 font-black">{formatNumber(row.stockTotal)}</p></div><div className="rounded-xl bg-muted/30 px-3 py-2"><p className="text-muted-foreground">Disponible</p><p className="mt-1 font-black text-emerald-600">{formatNumber(row.availableTotal)}</p></div></div><p className="mt-4 text-xs text-muted-foreground">{row.isCorporate ? 'Sucursales que puede abastecer:' : 'Sucursal propietaria:'}</p><div className="mt-2 flex flex-wrap gap-1.5">{row.branches.map((branch: any) => <Badge key={branch.id} variant="secondary" className="max-w-full truncate">{branch.name}</Badge>)}{!row.branches.length && <span className="text-xs text-muted-foreground">Sin sucursal vinculada</span>}</div></button>)}</CardContent></Card>;
  if (view === 'audits') return <SimpleTable title="Recuento de auditorías" headers={['Acta', 'Fecha', 'Sucursal', 'Ubicación', 'Responsable', 'Productos', 'Diferencia', 'Estado']} rows={rows} onDetail={onDetail} render={(row) => [row.number, formatDate(row.auditDate), row.branchName, row.warehouseName, row.supervisorName || row.stockKeeperName || '—', formatNumber(row.itemCount), formatNumber(row.difference), formatStatus(row.status)]} />;
  if (view === 'losses') return <SimpleTable title="Pérdidas registradas" headers={['Ajuste', 'Fecha', 'Sucursal', 'Ubicación', 'Unidades', 'Monto', 'Motivo']} rows={rows} onDetail={onDetail} render={(row) => [row.number, formatDate(row.date), row.branchName, row.warehouseName, formatNumber(row.lossUnits), formatMoney(row.lossAmount), row.reason || '—']} />;
  if (view === 'movements') return <SimpleTable title="Kardex por ubicación" headers={['Fecha', 'Producto', 'Sucursal', 'Ubicación', 'Tipo', 'Cantidad', 'Saldo resultante', 'Referencia']} rows={rows} onDetail={onDetail} render={(row) => [formatDate(row.date), `${row.product?.code || '—'} · ${row.product?.name || 'Producto'}`, row.branchName, row.warehouse?.name || '—', formatStatus(row.type), formatNumber(row.quantity), formatNumber(row.resultingQty), row.reference || '—']} />;
  return <SimpleTable title="Mobiliario y equipos" headers={['Código', 'Activo', 'Categoría', 'Sucursal', 'Estado', 'Costo', 'Ubicación']} rows={rows} onDetail={onDetail} render={(row) => [row.code, row.name, row.category, row.branchName, formatStatus(row.status), formatMoney(row.cost, row.currency || 'NIO'), row.location || '—']} />;
}

function SimpleTable({ title, headers, rows, render, onDetail }: { title: string; headers: string[]; rows: any[]; render: (row: any) => unknown[]; onDetail: (row: any) => void }) {
  return <Card className="rounded-3xl border-border/60 shadow-sm"><CardHeader><CardTitle className="text-lg font-black uppercase italic tracking-tight">{title}</CardTitle></CardHeader><CardContent className="p-0"><ResponsiveTable><TableHeader><TableRow>{headers.map((header) => <TableHead key={header}>{header}</TableHead>)}<TableHead /></TableRow></TableHeader><TableBody>{rows.map((row) => <TableRow key={row.id}>{render(row).map((cell, index) => <TableCell key={`${row.id}-${index}`} className="max-w-56 truncate">{String(cell ?? '—')}</TableCell>)}<TableCell className="text-right"><Button variant="ghost" size="sm" className="rounded-lg" onClick={() => onDetail(row)}><Eye className="mr-1.5 size-4" />Detalle</Button></TableCell></TableRow>)}</TableBody></ResponsiveTable></CardContent></Card>;
}

function ResponsiveTable({ children }: { children: ReactNode }) { return <div className="sales-responsive-table overflow-x-auto"><Table className="min-w-[980px]">{children}</Table></div>; }
function FilterSelect({ label, value, onChange, options }: { label: string; value: string; onChange: (value: string) => void; options: Array<{ value: string; label: string }> }) { return <label className="min-w-0 space-y-1.5 text-xs font-bold text-muted-foreground"><span>{label}</span><select value={value} onChange={(event) => onChange(event.target.value)} className="h-9 w-full min-w-0 rounded-md border border-border bg-background px-3 text-sm font-normal text-foreground outline-none focus-visible:border-primary focus-visible:ring-2 focus-visible:ring-primary/30"><option value="">Todos</option>{options.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select></label>; }
function DateFilter({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label className="min-w-0 space-y-1.5 text-xs font-bold text-muted-foreground"><span>{label}</span><div className="relative"><CalendarDays className="pointer-events-none absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><Input type="date" value={value} onChange={(event) => onChange(event.target.value)} className="pl-9" /></div></label>; }
function SelectField({ label, value, onChange, options }: { label: string; value: string; onChange: (value: string) => void; options: Array<{ value: string; label: string }> }) { return <label className="min-w-0 space-y-1.5 text-xs font-bold text-muted-foreground"><span>{label}</span><select value={value} onChange={(event) => onChange(event.target.value)} className="h-10 w-full min-w-0 rounded-xl border border-border bg-background px-3 text-sm font-normal text-foreground"><option value="">Seleccionar</option>{options.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select></label>; }
function Pagination({ page, totalPages, onChange }: { page: number; totalPages: number; onChange: (page: number) => void }) { return <div className="flex flex-wrap items-center justify-between gap-3 text-sm"><span className="text-muted-foreground">Página {page} de {totalPages}</span><div className="flex gap-2"><Button variant="outline" size="sm" className="rounded-lg" disabled={page <= 1} onClick={() => onChange(page - 1)}>Anterior</Button><Button variant="outline" size="sm" className="rounded-lg" disabled={page >= totalPages} onClick={() => onChange(page + 1)}>Siguiente</Button></div></div>; }
function DetailDialog({ view, row, onClose }: { view: ManagerInventoryView; row: any | null; onClose: () => void }) { return <Dialog open={Boolean(row)} onOpenChange={(open) => !open && onClose()}><DialogContent className="max-w-5xl rounded-3xl"><DialogHeader><DialogTitle className="text-xl font-black uppercase italic">Detalle · {viewLabels[view]}</DialogTitle><DialogDescription>Consulta de solo lectura. Los stocks de sucursal y almacén corporativo no se consolidan.</DialogDescription></DialogHeader>{row && <div className="max-h-[65vh] space-y-4 overflow-y-auto">{view === 'branchInventory' || view === 'corporateInventory' ? <InfoGrid items={[["Producto", row.name], ["Código", row.code], ["SKU", row.sku || '—'], ["Sucursal", row.branchName], ["Ubicación", row.warehouseName], ["Stock", formatNumber(row.quantity)], ["Reservado", formatNumber(row.reserved)], ["Disponible", formatNumber(row.available)]]} /> : view === 'products' || view === 'services' ? <><InfoGrid items={[["Sucursal", row.branchName || '—'], ["Código", row.code], ["Nombre", row.name], ["Categoría", row.category], ["Unidad", row.unit], ["Costo", formatMoney(row.costPrice)], ["Disponible", view === 'products' ? formatNumber(row.branchAvailable) : '—']]} /><DetailList title="Desglose por sucursal y ubicación" rows={row.locations.map((location: any) => `${location.branchName} · ${location.warehouseName} · ${formatNumber(location.quantity)} unidades (${formatNumber(location.available)} disponibles)`)} /><DetailList title="Precios por sucursal" rows={row.pricesByBranch.map((price: any) => `${price.branchName}: ${formatMoney(price.price, price.currency)}`)} /></> : view === 'warehouses' ? <><InfoGrid items={[["Almacén / bodega", row.name], ["Rubro", row.businessUnitName || '—'], ["Tipo", row.isCorporate ? 'Corporativo' : 'Bodega de sucursal'], ["Ubicación", row.location || '—'], ["Stock visible", formatNumber(row.stockTotal)], ["Disponible", formatNumber(row.availableTotal)]]} /><DetailList title={row.isCorporate ? "Sucursales abastecidas" : "Sucursal propietaria"} rows={row.branches.map((branch: any) => branch.name)} /></> : <pre className="overflow-x-auto rounded-2xl border border-border/60 bg-muted/20 p-4 text-xs leading-5">{JSON.stringify(row, null, 2)}</pre>}</div>}<DialogFooter><Button type="button" variant="outline" className="rounded-xl" onClick={onClose}>Cerrar</Button></DialogFooter></DialogContent></Dialog>; }
function InfoGrid({ items }: { items: Array<[string, unknown]> }) { return <div className="grid grid-cols-1 gap-3 rounded-2xl border border-border/60 bg-muted/20 p-4 sm:grid-cols-2 lg:grid-cols-3">{items.map(([label, value]) => <div key={label}><p className="text-[10px] font-black uppercase tracking-widest text-muted-foreground">{label}</p><p className="mt-1 truncate text-sm font-semibold">{String(value ?? '—')}</p></div>)}</div>; }
function DetailList({ title, rows }: { title: string; rows: string[] }) { return <div className="rounded-2xl border border-border/60 p-4"><p className="text-xs font-black uppercase tracking-widest text-muted-foreground">{title}</p><div className="mt-3 space-y-2">{rows.length ? rows.map((row, index) => <div key={`${row}-${index}`} className="rounded-xl bg-muted/30 px-3 py-2 text-sm">{row}</div>) : <p className="text-sm text-muted-foreground">Sin información.</p>}</div></div>; }
function warehousesForBranch(warehouses: WarehouseOption[], branchId: string) { return warehouses.filter((warehouse) => warehouse.clientTenantId === branchId || warehouse.authorizedBranchIds?.includes(branchId)); }
function exportRow(view: ManagerInventoryView, row: any) { if (view === 'branchInventory' || view === 'corporateInventory') return { Alcance: view === 'branchInventory' ? 'Mi sucursal' : 'Almacén corporativo', Código: row.code, Producto: row.name, SKU: row.sku, Sucursal: row.branchName, Ubicación: row.warehouseName, Stock: row.quantity, Reservado: row.reserved, Disponible: row.available }; if (view === 'products' || view === 'services') return { Sucursal: row.branchName, Código: row.code, Nombre: row.name, Categoría: row.category, Unidad: row.unit, Costo: row.costPrice, 'Stock de sucursal': row.branchStock, Disponible: row.branchAvailable, Ubicaciones: row.locationCount, Desglose: row.locations.map((location: any) => `${location.branchName} / ${location.warehouseName}: ${location.quantity}`).join(' | ') }; if (view === 'warehouses') return { Nombre: row.name, Rubro: row.businessUnitName, Tipo: row.isCorporate ? 'Corporativo' : 'Bodega de sucursal', Sucursales: row.branches.map((branch: any) => branch.name).join(', '), Ubicación: row.location, 'Stock visible': row.stockTotal, Disponible: row.availableTotal }; if (view === 'transfers') return { Número: row.number, Fecha: formatDate(row.date), Origen: row.from?.name, Destino: row.to?.name, Estado: formatStatus(row.status), Productos: row.itemCount, Unidades: row.units }; if (view === 'audits') return { Acta: row.number, Fecha: formatDate(row.auditDate), Sucursal: row.branchName, Ubicación: row.warehouseName, Estado: formatStatus(row.status), Productos: row.itemCount, Diferencia: row.difference }; if (view === 'losses') return { Ajuste: row.number, Fecha: formatDate(row.date), Sucursal: row.branchName, Unidades: row.lossUnits, Monto: row.lossAmount, Motivo: row.reason }; if (view === 'movements') return { Fecha: formatDate(row.date), Código: row.product?.code, Producto: row.product?.name, Sucursal: row.branchName, Ubicación: row.warehouse?.name, Tipo: formatStatus(row.type), Cantidad: row.quantity, Saldo: row.resultingQty, Referencia: row.reference }; return { Código: row.code, Activo: row.name, Categoría: row.category, Sucursal: row.branchName, Estado: formatStatus(row.status), Costo: row.cost, Ubicación: row.location };
}
