const fs = require('fs');
const file = 'c:/Users/rafae/OneDrive/Desktop/Proyectos/ERP-NovaHub/Frontend/novahub-frontend/src/app/components/auth/RegisterTenantPage.tsx';
let code = fs.readFileSync(file, 'utf8');

if (!code.includes('SUBMODULE_NAMES_ES')) {
  const dictionary = `
const SUBMODULE_NAMES_ES: Record<string, string> = {
  SALES_CLIENTS: 'Clientes',
  SALES_QUOTES: 'Cotizaciones',
  SALES_ORDERS: 'Pedidos',
  SALES_INVOICES: 'Facturación',
  SALES_RECURRING: 'Ventas Recurrentes',
  SALES_PAYMENTS: 'Pagos Recibidos',
  SALES_RETURNS: 'Devoluciones',
  SALES_CREDIT_NOTES: 'Notas de Crédito',
  SALES_COMMISSIONS: 'Comisiones',
  PURCHASES_PROVIDERS: 'Proveedores',
  PURCHASES_EXPENSES: 'Gastos',
  PURCHASES_EXPENSES_REC: 'Gastos Recurrentes',
  PURCHASES_REQUESTS: 'Solicitudes',
  PURCHASES_QUOTES: 'Cotizaciones',
  PURCHASES_ORDERS: 'Órdenes de Compra',
  PURCHASES_RECEIPTS: 'Recibos',
  PURCHASES_INVOICES: 'Facturas',
  PURCHASES_INVOICES_REC: 'Facturas Recurrentes',
  PURCHASES_RETURNS: 'Devoluciones',
  PURCHASES_PAYMENTS: 'Pagos Emitidos',
  INVENTORY_PRODUCTS: 'Productos',
  INVENTORY_WAREHOUSES: 'Almacenes',
  INVENTORY_TRANSFERS: 'Transferencias',
  INVENTORY_ADJUSTMENTS: 'Ajustes',
  INVENTORY_MOVEMENTS: 'Movimientos',
  INVENTORY_COUNT: 'Conteo Físico',
  INVENTORY_SERIALS: 'Números de Serie',
  INVENTORY_LOTS: 'Lotes',
  INVENTORY_DASHBOARD: 'Dashboard',
  FINANCIAL_ACCOUNTS: 'Cuentas',
  FINANCIAL_JOURNAL: 'Diario',
  FINANCIAL_LEDGER: 'Libro Mayor',
  FINANCIAL_BANK: 'Bancos',
  FINANCIAL_BUDGET: 'Presupuestos',
  FINANCIAL_REPORTS: 'Reportes',
  FINANCIAL_INCOMES: 'Ingresos',
  FINANCIAL_EXPENSES: 'Gastos',
  FINANCIAL_EXPENSES_REC: 'Gastos Recurrentes',
  FINANCIAL_BALANCE: 'Balance',
  FINANCIAL_DASHBOARD: 'Dashboard',
  FINANCIAL_INCOMES_REC: 'Ingresos Recurrentes',
  HR_EMPLOYEES: 'Empleados',
  HR_PAYROLL: 'Nómina',
  HR_ATTENDANCE: 'Asistencia',
  HR_LEAVES: 'Permisos',
  HR_PERFORMANCE: 'Desempeño',
  HR_TRAINING: 'Capacitación',
  HR_BENEFITS: 'Beneficios',
  HR_DASHBOARD: 'Dashboard',
  HR_PAYROLL_CONFIG: 'Config. Nómina',
  PROJECTS_LIST: 'Proyectos',
  PROJECTS_TASKS: 'Tareas',
  PROJECTS_MILESTONES: 'Hitos',
  REPORTS_SALES: 'Ventas',
  REPORTS_FINANCIAL: 'Finanzas',
  REPORTS_INVENTORY: 'Inventario',
  REPORTS_PURCHASES: 'Compras',
  REPORTS_CLIENTS: 'Clientes',
  REPORTS_PROVIDERS: 'Proveedores',
  REPORTS_HR: 'Recursos Humanos',
  REPORTS_SUBSCRIPTIONS: 'Suscripciones',
  DOCUMENTS_FILES: 'Archivos',
  DOCUMENTS_FOLDERS: 'Carpetas',
  DOCUMENTS_CONTRACTS: 'Contratos',
  DOCUMENTS_INVOICES: 'Facturas',
  DOCUMENTS_REPORTS: 'Reportes',
  ACTIVITIES_TASKS: 'Tareas',
  ACTIVITIES_EVENTS: 'Eventos',
  ACTIVITIES_REMINDERS: 'Recordatorios',
  ACTIVITIES_BITACORA: 'Bitácora',
  ACTIVITIES_LOGS: 'Registros',
  ACTIVITIES_CALENDAR: 'Calendario',
  ACTIVITIES_MEETINGS: 'Reuniones',
  CONFIG_COMPANY: 'Empresa',
  CONFIG_BRANDING: 'Branding',
  CONFIG_ROLES: 'Roles',
  CONFIG_SECURITY: 'Seguridad',
  CONFIG_CURRENCY: 'Monedas',
  CONFIG_USERS: 'Usuarios',
  CONFIG_SUBSCRIPTION: 'Suscripción',
  CONFIG_TENANCY: 'Tenancy',
  CONFIG_PLATFORM: 'Plataforma',
  CONFIG_DOMAINS: 'Dominios',
  NOTIFICATIONS_ALERTS: 'Alertas',
  NOTIFICATIONS_MESSAGES: 'Mensajes',
  NOTIFICATIONS_PUSH: 'Notificaciones Push',
  ACCOUNTING_CHART: 'Plan de Cuentas',
  ACCOUNTING_JOURNAL: 'Libro Diario',
};
const PARENT_KEYS = new Set(Object.keys(PARENT_SUBMODULES));`;

  code = code.replace('const PARENT_KEYS = new Set(Object.keys(PARENT_SUBMODULES));', dictionary);
}

const oldRender = "{subInfo?.name || subKey.replace(/_/g, ' ').toLowerCase().replace(/\\b\\w/g, (c: string) => c.toUpperCase())}";
const newRender = "{SUBMODULE_NAMES_ES[subKey] || subInfo?.name || subKey.replace(/_/g, ' ').toLowerCase().replace(/\\b\\w/g, (c: string) => c.toUpperCase())}";

code = code.replace(oldRender, newRender);

fs.writeFileSync(file, code);
console.log('Translated submodules');
