/**
 * Etiquetas de estado para documentos PDF.
 *
 * Los estados se almacenan como enums en inglés para mantener estable el
 * contrato de la API. Esta traducción pertenece únicamente a la salida
 * visible y es deliberadamente idempotente para que también acepte valores
 * que ya fueron traducidos por una vista.
 */
const PDF_STATUS_LABELS: Record<string, string> = {
  DRAFT: 'Borrador',
  BORRADOR: 'Borrador',
  IN_PROCESS: 'En proceso',
  EN_PROCESO: 'En proceso',
  IN_PROGRESS: 'En proceso',
  PENDING: 'Pendiente',
  PENDIENTE: 'Pendiente',
  PENDING_REVIEW: 'Pendiente de revisión',
  PENDIENTE_DE_REVISION: 'Pendiente de revisión',
  PENDING_APPROVAL: 'Pendiente de aprobación',
  PENDIENTE_DE_APROBACION: 'Pendiente de aprobación',
  SENT: 'Enviada',
  ENVIADA: 'Enviada',
  SUBMITTED: 'Enviada',
  ACCEPTED: 'Aceptada',
  ACEPTADA: 'Aceptada',
  APPROVED: 'Aprobada',
  APROBADA: 'Aprobada',
  APROBADO: 'Aprobado',
  REJECTED: 'Rechazada',
  RECHAZADA: 'Rechazada',
  RECHAZADO: 'Rechazado',
  CANCELLED: 'Cancelada',
  CANCELADA: 'Cancelada',
  CANCELADO: 'Cancelado',
  CONFIRMED: 'Confirmada',
  CONFIRMADA: 'Confirmada',
  SHIPPED: 'Enviada',
  DELIVERED: 'Entregada',
  PARTIAL: 'Pago parcial',
  PARCIAL: 'Pago parcial',
  PARTIALLY_PAID: 'Pago parcial',
  PAID: 'Pagada',
  PAGADA: 'Pagada',
  CREDIT: 'A crédito',
  A_CREDITO: 'A crédito',
  OVERDUE: 'Vencida',
  VENCIDA: 'Vencida',
  REFUNDED: 'Reembolsada',
  REQUESTED: 'Solicitada',
  SOLICITADA: 'Solicitada',
  CANCELED: 'Cancelada',
  ISSUED: 'Emitida',
  EMITIDA: 'Emitida',
  APPLIED: 'Aplicada',
  APLICADA: 'Aplicada',
  VOIDED: 'Anulada',
  ANULADA: 'Anulada',
  CLAIMED: 'Asignada',
  RECEIVED: 'Recibida',
  RECIBIDA: 'Recibida',
  WITH_INCIDENTS: 'Con incidencias',
  CON_INCIDENCIAS: 'Con incidencias',
  PROCESSED: 'Procesada',
  PROCESADA: 'Procesada',
  ACTIVE: 'Activa',
  ACTIVO: 'Activo',
  ACTIVA: 'Activa',
  INACTIVE: 'Inactiva',
  INACTIVO: 'Inactivo',
  INACTIVA: 'Inactiva',
  ARCHIVED: 'Archivada',
  ARCHIVADO: 'Archivado',
  ARCHIVADA: 'Archivada',
  PAUSED: 'Pausada',
  PAUSADO: 'Pausado',
  PAUSADA: 'Pausada',
  EXPIRED: 'Vencida',
  VENCIDO: 'Vencido',
  OPEN: 'Abierta',
  ABIERTA: 'Abierta',
  COUNTING: 'En arqueo',
  EN_ARQUEO: 'En arqueo',
  CLOSED: 'Cerrada',
  CERRADA: 'Cerrada',
  SUCCESS: 'Completada',
  COMPLETED: 'Completada',
  COMPLETADA: 'Completada',
  FAILED: 'Fallida',
  FALLIDA: 'Fallida',
  SKIPPED: 'Omitida',
  OMITIDA: 'Omitida',
  POSTED: 'Contabilizado',
  CONTABILIZADO: 'Contabilizado',
  PROCESSING: 'En proceso',
  SUSPENDED: 'Suspendida',
  SUSPENDIDA: 'Suspendida',
  IN_TRANSIT: 'En tránsito',
  EN_TRANSITO: 'En tránsito',
  RESOLVED: 'Resuelta',
  RESUELTA: 'Resuelta',
  LOCKED: 'Bloqueada',
  BLOQUEADA: 'Bloqueada',
  COLLECTED: 'Cobrado',
  COBRADO: 'Cobrado',
  WRITTEN_OFF: 'Dado de baja',
  DADO_DE_BAJA: 'Dado de baja',
  DEPRECIATED: 'Depreciado',
  DEPRECIADO: 'Depreciado',
  DISPOSED: 'Dado de baja',
  ON_LEAVE: 'De permiso',
  DE_PERMISO: 'De permiso',
  TERMINATED: 'Retirado',
  RETIRADO: 'Retirado',
  PRESENT: 'Presente',
  PRESENTE: 'Presente',
  ABSENT: 'Ausente',
  AUSENTE: 'Ausente',
  LATE: 'Tarde',
  TARDE: 'Tarde',
  REMOTE: 'Remoto',
  REMOTO: 'Remoto',
  HALF_DAY: 'Medio día',
  MEDIO_DIA: 'Medio día',
  SCHEDULED: 'Programada',
  PROGRAMADA: 'Programada',
  WAITING_DOCS: 'Esperando documentos',
  ESPERANDO_DOCUMENTOS: 'Esperando documentos',
  AVAILABLE: 'Disponible',
  DISPONIBLE: 'Disponible',
  OCCUPIED: 'Ocupada',
  OCUPADA: 'Ocupada',
  RESERVED: 'Reservada',
  RESERVADA: 'Reservada',
  CLEANING: 'En limpieza',
  EN_LIMPIEZA: 'En limpieza',
  SERVED: 'Servida',
  SERVIDA: 'Servida',
  READY: 'Lista',
  LISTA: 'Lista',
  SENT_TO_KITCHEN: 'Enviada a cocina',
  ENVIADA_A_COCINA: 'Enviada a cocina',
  IN_PREPARATION: 'En preparación',
  EN_PREPARACION: 'En preparación',
  PENDING_CONFIRMATION: 'Pendiente de confirmación',
  PENDIENTE_DE_CONFIRMACION: 'Pendiente de confirmación',
  NEW: 'Nuevo',
  NUEVO: 'Nuevo',
  CONTACTED: 'Contactado',
  CONTACTADO: 'Contactado',
  QUALIFIED: 'Calificado',
  CALIFICADO: 'Calificado',
  CONVERTED: 'Convertido',
  CONVERTIDO: 'Convertido',
  LOW: 'Baja',
  MEDIUM: 'Media',
  HIGH: 'Alta',
  URGENT: 'Urgente',
  VERY_URGENT: 'Muy urgente',
  RETURNED_FOR_CORRECTION: 'Devuelta para corrección',
  DEVUELTA_PARA_CORRECCION: 'Devuelta para corrección',
  IN_REVIEW: 'En revisión',
  EN_REVISION: 'En revisión',
  IN_QUOTATION: 'En cotización',
  EN_COTIZACION: 'En cotización',
  CONVERTED_TO_ORDER: 'Convertida en orden',
  CONVERTIDA_EN_ORDEN: 'Convertida en orden',
  COMPLETE: 'Completa',
  COMPLETA: 'Completa',
  INCOMPLETE: 'Incompleta',
  INCOMPLETA: 'Incompleta',
  OK: 'Normal',
  NORMAL: 'Normal',
  LOW_STOCK: 'Stock bajo',
  STOCK_BAJO: 'Stock bajo',
  OUT_OF_STOCK: 'Agotado',
  AGOTADO: 'Agotado',
  NO_SALES: 'Sin ventas',
  MISSING_COST_CLASSIFICATION: 'Falta clasificación de costos',
  NON_POSITIVE_CONTRIBUTION_MARGIN: 'Margen no positivo',
  AVAILABLE_FOR_SALE: 'Disponible para venta',
  NO_APPLIES: 'No aplica',
  NO_APLICA: 'No aplica',
  ERROR: 'Error',
  WARNING: 'Advertencia',
};

function statusKey(value: string) {
  return value
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .trim()
    .replace(/[\s-]+/g, '_')
    .toUpperCase();
}

/** Devuelve siempre una etiqueta legible en español para un estado PDF. */
export function pdfStatusLabel(value: unknown, fallback = 'Estado no especificado') {
  if (value === null || value === undefined || String(value).trim() === '') return fallback;
  const raw = String(value).trim();
  const translated = PDF_STATUS_LABELS[statusKey(raw)];
  if (translated) return translated;

  // Un valor libre ya escrito como texto se conserva; un enum desconocido no
  // debe filtrarse al PDF en inglés ni con guiones bajos.
  if (!/^[A-Z0-9_ -]+$/.test(raw)) return raw;
  return fallback;
}
